import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AccountCreater from "@/components/AccountCreater";
import db from "@/moduls/db";
import { redirect } from "next/navigation";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TimeClientApps",
  description: "Generated by create next app",
};
type AccountsType = {
  id: string;
  name: string;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let accounts: AccountsType[] = [];
  try {
    accounts = await db.account.findMany({
      select: { id: true, name: true },
      orderBy: { name: "asc" },
    });
  } catch (error) {
    console.error(error);
  }

  return (
    <html lang="en">
      <body className={`flex min-h-screen  ${inter.className}`}>
        <div className="flex flex-col min-w-[380px] bg-gray-800 text-white text-center p-4">
          <AccountCreater />
          <div className="mt-4 py-2 border shadow-lg bg-gray-300 min-h-10 w-full">
            <h2 className="text-gray-800 font-medium">List of Accounts:</h2>
            <ul className="list-none p-2">
              {accounts.map((account) => (
                <li
                  className=" text-gray-400 hover:text-gray-700 cursor-pointer"
                  key={account.id}
                >
                  <Link href={`/accounts/${account.id}`}>{account.name}</Link>
                </li>
              ))}
            </ul>
          </div>
        </div>
        <div className="flex-1">{children}</div>
      </body>
    </html>
  );
}
